const OVERLAY_STYLE = `
<style id="smartMoneyObservationStyles">
:root{--status-bullish:#54dfa0;--status-bearish:#ff7f8c;--status-warning:#f5bf62;--status-scanning:#66b8ff;--status-special:#b992ff;--status-neutral:#8fa4bf;--status-disabled:#53677d;--status-danger:#ff4f63;--status-confirmed:#54dfa0}
.sm-observation-panel{margin-top:14px;padding:16px;border:1px solid rgba(67,121,161,.48);border-radius:18px;background:linear-gradient(145deg,rgba(8,29,47,.9),rgba(5,17,30,.96))}.sm-observation-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;flex-wrap:wrap}.sm-observation-head h3{margin:4px 0 0;font-size:19px}.sm-observation-lock{padding:7px 10px;border-radius:999px;border:1px solid #28684c;background:rgba(40,119,82,.15);color:#83e9b2;font-size:10px;font-weight:900}.sm-observation-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:12px}.sm-observation-metric{padding:10px;border:1px solid rgba(52,88,124,.4);border-radius:11px;background:rgba(7,21,37,.68)}.sm-observation-metric span{display:block;color:#8fa4bf;font-size:10px}.sm-observation-metric strong{display:block;margin-top:5px;font-size:13px}
.ti-selected-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:14px;padding:10px 12px;border:1px solid rgba(64,105,144,.42);border-radius:13px;background:rgba(5,18,32,.7)}.ti-selected-symbol{font-size:20px;font-weight:950}.ti-selected-meta{font-size:11px;color:#8fa4bf}.ti-shell{display:grid;grid-template-columns:minmax(230px,.42fr) minmax(0,1.58fr);gap:14px;margin-top:10px}.ti-master,.ti-grid-wrap{border:1px solid rgba(64,105,144,.42);border-radius:16px;background:rgba(4,15,27,.66);padding:14px}.ti-master{display:grid;place-items:center;align-content:center;min-height:320px}.ti-master h4{margin:11px 0 4px;font-size:17px}.ti-master-meta{display:flex;gap:7px;flex-wrap:wrap;justify-content:center;margin-top:10px}.ti-pill{padding:5px 8px;border:1px solid rgba(79,120,157,.45);border-radius:999px;color:#afc2d8;font-size:10px}.ti-grid{display:grid;grid-template-columns:repeat(4,minmax(135px,1fr));gap:10px}.ti-card{appearance:none;color:inherit;text-align:inherit;width:100%;padding:10px;border:1px solid rgba(57,95,132,.42);border-radius:14px;background:rgba(7,20,34,.76);min-width:0;cursor:pointer}.ti-card:hover,.ti-card:focus-visible,.ti-card.selected{border-color:#66b8ff;box-shadow:0 0 0 2px rgba(102,184,255,.16);outline:none}.ti-card-head{display:flex;justify-content:space-between;gap:7px;align-items:flex-start}.ti-card-title{font-size:11px;font-weight:900;line-height:1.25}.ti-status{font-size:8px;font-weight:900;padding:4px 5px;border-radius:999px;border:1px solid currentColor;white-space:nowrap}.ti-gauge{--gauge-score:0;--gauge-color:var(--status-neutral);width:112px;height:112px;border-radius:50%;margin:10px auto 7px;display:grid;place-items:center;position:relative;background:conic-gradient(var(--gauge-color) calc(var(--gauge-score)*1%),rgba(75,102,128,.18) 0);transition:background .45s ease}.ti-gauge:before{content:"";position:absolute;inset:10px;border-radius:50%;background:#071421;border:1px solid rgba(85,117,147,.38)}.ti-gauge-core{position:relative;z-index:1;text-align:center}.ti-score{display:block;font-size:24px;font-weight:950}.ti-direction{display:block;font-size:9px;color:#a8bdd4;margin-top:2px}.ti-confidence{display:block;font-size:9px;color:#718aa5;margin-top:3px}.ti-summary{font-size:10px;line-height:1.45;color:#9eb2c8;min-height:43px}.ti-unavailable .ti-gauge{filter:saturate(.2);opacity:.7}.ti-active .ti-gauge:after{content:"";position:absolute;inset:-4px;border:1px solid var(--gauge-color);border-radius:50%;animation:tiPulse 2s ease-in-out infinite}.ti-status.CONFIRMED{color:var(--status-confirmed)}.ti-status.REJECTED,.ti-status.BLOCKED,.ti-status.ERROR,.ti-status.CONFLICTING{color:var(--status-bearish)}.ti-status.WAITING_FOR_CONFIRMATION,.ti-status.DEVELOPING{color:var(--status-warning)}.ti-status.UNAVAILABLE,.ti-status.DISABLED{color:var(--status-disabled)}.ti-status.SCANNING,.ti-status.VALIDATING{color:var(--status-scanning)}
.ti-flow{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin:12px 0 0}.ti-flow-step{padding:7px 9px;border-radius:10px;border:1px solid rgba(67,103,138,.42);font-size:9px;font-weight:850;color:#8fa4bf}.ti-flow-step.pass{color:#83e9b2;border-color:#28684c}.ti-flow-step.fail{color:#ff9da7;border-color:#8a3b46}.ti-flow-arrow{color:#58718c}.ti-detail{margin-top:12px;padding:14px;border:1px solid rgba(64,105,144,.42);border-radius:15px;background:rgba(5,18,32,.78)}.ti-detail-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.ti-detail-head h4{margin:3px 0 0}.ti-detail-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:12px}.ti-detail-cell{padding:9px;border:1px solid rgba(54,90,126,.38);border-radius:10px;background:rgba(7,21,37,.7)}.ti-detail-cell span{display:block;color:#7890aa;font-size:9px}.ti-detail-cell strong{display:block;margin-top:4px;font-size:11px;overflow-wrap:anywhere}.ti-detail-lists{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:10px}.ti-detail-list{padding:10px;border:1px solid rgba(54,90,126,.38);border-radius:10px}.ti-detail-list strong{font-size:10px}.ti-detail-list ul{margin:7px 0 0;padding-inline-start:18px;color:#9eb2c8;font-size:10px;line-height:1.55}.ti-detail-json{margin-top:10px;padding:10px;border-radius:10px;background:#04101d;border:1px solid rgba(54,90,126,.38);font:10px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;color:#9eb2c8;white-space:pre-wrap;overflow-wrap:anywhere;max-height:190px;overflow:auto}
.sm-stage-distribution{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin-top:9px}.sm-stage-box{padding:8px;border:1px solid rgba(52,88,124,.36);border-radius:10px;background:rgba(5,18,32,.58);text-align:center}.sm-stage-box span{display:block;color:#7890aa;font-size:9px}.sm-stage-box strong{display:block;margin-top:4px;font-size:13px}.sm-opportunity-list{display:grid;gap:8px;margin-top:12px}.sm-opportunity{appearance:none;color:inherit;text-align:inherit;width:100%;display:grid;grid-template-columns:88px minmax(160px,1.2fr) repeat(5,minmax(78px,.55fr));gap:8px;align-items:center;padding:10px;border:1px solid rgba(52,88,124,.4);border-radius:11px;background:rgba(5,18,32,.7);cursor:pointer}.sm-opportunity:hover,.sm-opportunity:focus-visible,.sm-opportunity.selected{border-color:#66b8ff;outline:none;box-shadow:0 0 0 2px rgba(102,184,255,.13)}.sm-opportunity.passed{border-color:rgba(45,121,88,.72);background:rgba(8,35,29,.65)}.sm-opportunity-symbol{font-size:16px;font-weight:950}.sm-opportunity-family{font-size:11px;color:#a9bdd4}.sm-opportunity-cell span{display:block;color:#7890aa;font-size:9px}.sm-opportunity-cell strong{display:block;margin-top:3px;font-size:11px}.sm-observation-empty{padding:14px;text-align:center;color:#8fa4bf;border:1px dashed rgba(60,96,131,.45);border-radius:11px}.sm-stage-pass{color:#83e9b2}.sm-stage-fail{color:#ff9da7}.sm-stage-watch{color:#9cd3ff}
@keyframes tiPulse{0%,100%{opacity:.25;transform:scale(.98)}50%{opacity:.8;transform:scale(1.025)}}@media(prefers-reduced-motion:reduce){.ti-gauge,.ti-active .ti-gauge:after{animation:none!important;transition:none!important}}@media(max-width:1250px){.ti-grid{grid-template-columns:repeat(3,minmax(135px,1fr))}.sm-observation-summary,.sm-stage-distribution{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.ti-shell{grid-template-columns:1fr}.ti-master{min-height:250px}.ti-grid{grid-template-columns:repeat(2,minmax(135px,1fr))}.ti-detail-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ti-detail-lists{grid-template-columns:1fr}.sm-opportunity{grid-template-columns:80px 1fr repeat(3,minmax(75px,.55fr))}.sm-opportunity-cell:nth-last-child(-n+2){display:none}}@media(max-width:600px){.sm-observation-summary,.sm-stage-distribution,.ti-detail-grid{grid-template-columns:repeat(2,1fr)}.ti-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ti-gauge{width:94px;height:94px}.ti-score{font-size:20px}.sm-opportunity{grid-template-columns:72px 1fr}.sm-opportunity-cell{display:none}}
</style>`;

const OVERLAY_SCRIPT = `
<script id="smartMoneyObservationScript">
(function(){
  const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
  const stageLabels={STOP_RUN:'STOP RUN',ABSORPTION:'ABSORPTION',IMBALANCE:'IMBALANCE',STRUCTURE_CONFIRMATION:'STRUCTURE',RISK_ENGINE:'RISK'};
  const state={items:[],selectedSymbol:null,selectedGauge:null,latest:null};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const cash=value=>Number.isFinite(Number(value))?money.format(Number(value)):'—';
  const number=(value,digits=1)=>Number.isFinite(Number(value))?Number(value).toFixed(digits):'—';
  const list=value=>Array.isArray(value)?value:[];
  const gaugeColor=g=>g.status==='CONFIRMED'?(g.direction==='SHORT'?'var(--status-bearish)':'var(--status-confirmed)'):['REJECTED','BLOCKED','ERROR','CONFLICTING'].includes(g.status)?'var(--status-bearish)':['WAITING_FOR_CONFIRMATION','DEVELOPING'].includes(g.status)?'var(--status-warning)':['SCANNING','VALIDATING'].includes(g.status)?'var(--status-scanning)':g.id==='smt-divergence'?'var(--status-special)':'var(--status-neutral)';
  function ensurePanel(){if(document.getElementById('smartMoneyObservationPanel'))return document.getElementById('smartMoneyObservationPanel');const scanner=document.getElementById('scanner');if(!scanner)return null;const panel=document.createElement('div');panel.id='smartMoneyObservationPanel';panel.className='sm-observation-panel';panel.innerHTML='<div class="sm-observation-head"><div><span class="eyebrow">CIRCULAR TRADING INTELLIGENCE</span><h3>Institutional Flow Command Center</h3><p class="muted">اختر سهمًا ثم اختر عدادًا لعرض الأدلة والتعارضات والبيانات المصدرية.</p></div><span class="sm-observation-lock">OBSERVATION ONLY</span></div><div id="smartMoneyObservationContent"><div class="sm-observation-empty">بانتظار أول فحص Institutional Flow.</div></div>';scanner.appendChild(panel);return panel;}
  function stageDistribution(latest){const order=Array.isArray(latest?.stageOrder)&&latest.stageOrder.length?latest.stageOrder:Object.keys(stageLabels);const values=latest?.stageDistribution||{};return '<div class="sm-stage-distribution">'+order.map(name=>'<div class="sm-stage-box"><span>'+esc(stageLabels[name]||name)+'</span><strong>'+esc(values[name]??0)+'</strong></div>').join('')+'</div>';}
  function gaugeMarkup(g){const score=Number.isFinite(Number(g.score))?Math.max(0,Math.min(100,Number(g.score))):0;const scoreText=Number.isFinite(Number(g.score))?number(g.score,0):'—';const confidence=Number.isFinite(Number(g.confidence))?number(g.confidence,0)+'%':'Unavailable';const aria=esc(g.name+', score '+(scoreText==='—'?'unavailable':scoreText+' out of 100')+', '+g.direction+', '+g.status);return '<button type="button" class="ti-card '+(g.activity?'ti-active ':'')+(g.status==='UNAVAILABLE'?'ti-unavailable ':'')+(state.selectedGauge===g.id?'selected':'')+'" data-gauge-id="'+esc(g.id)+'" aria-label="'+aria+'"><div class="ti-card-head"><span class="ti-card-title">'+esc(g.name)+'</span><span class="ti-status '+esc(g.status)+'">'+esc(g.status.replaceAll('_',' '))+'</span></div><div class="ti-gauge" style="--gauge-score:'+score+';--gauge-color:'+gaugeColor(g)+'"><div class="ti-gauge-core"><span class="ti-score">'+scoreText+'</span><span class="ti-direction">'+esc(g.direction)+'</span><span class="ti-confidence">'+esc(confidence)+'</span></div></div><div class="ti-summary">'+esc(g.summary||'No explanation available.')+'</div></button>';}
  function detailList(title,items){const values=list(items);return '<div class="ti-detail-list"><strong>'+esc(title)+'</strong>'+(values.length?'<ul>'+values.map(item=>'<li>'+esc(item)+'</li>').join('')+'</ul>':'<div class="muted" style="margin-top:7px;font-size:10px">None reported</div>')+'</div>';}
  function safeMetadata(value){try{return JSON.stringify(value||{},null,2).slice(0,5000);}catch{return '{}';}}
  function detailMarkup(g){if(!g)return '<section class="ti-detail"><div class="muted">اختر عدادًا لعرض تفاصيله.</div></section>';return '<section class="ti-detail" aria-live="polite"><div class="ti-detail-head"><div><span class="eyebrow">GAUGE DETAIL</span><h4>'+esc(g.name)+'</h4><p class="muted">'+esc(g.summary||'No explanation available.')+'</p></div><span class="ti-status '+esc(g.status)+'">'+esc(g.status.replaceAll('_',' '))+'</span></div><div class="ti-detail-grid"><div class="ti-detail-cell"><span>SCORE</span><strong>'+number(g.score,0)+'</strong></div><div class="ti-detail-cell"><span>CONFIDENCE</span><strong>'+number(g.confidence,0)+'%</strong></div><div class="ti-detail-cell"><span>DIRECTION</span><strong>'+esc(g.direction)+'</strong></div><div class="ti-detail-cell"><span>TIMEFRAME</span><strong>'+esc(g.timeframe||'—')+'</strong></div><div class="ti-detail-cell"><span>CONTRIBUTION</span><strong>'+number(g.contribution,2)+'</strong></div><div class="ti-detail-cell"><span>WEIGHT</span><strong>'+number(g.weight,2)+'</strong></div><div class="ti-detail-cell"><span>MANDATORY</span><strong>'+(g.mandatory?'YES':'NO')+'</strong></div><div class="ti-detail-cell"><span>BLOCKS EXECUTION</span><strong>'+(g.blocksExecution?'YES':'NO')+'</strong></div></div><div class="ti-detail-lists">'+detailList('Confirmation reasons',g.confirmationReasons)+detailList('Penalties',g.penalties)+detailList('Blockers',g.blockers)+'</div><pre class="ti-detail-json">'+esc(safeMetadata(g.metadata))+'</pre></section>';}
  function intelligenceMarkup(item){const ti=item?.tradingIntelligence;if(!ti)return '<div class="sm-observation-empty">Gauge contract is not available for this result.</div>';const master=ti.tradeReadiness||{};const masterGauge={score:master.score,direction:master.direction,status:master.status};const gauges=Array.isArray(ti.gauges)?ti.gauges:[];if(!state.selectedGauge||!gauges.some(g=>g.id===state.selectedGauge))state.selectedGauge=gauges.find(g=>g.blocksExecution)?.id||gauges[0]?.id||null;const selectedGauge=gauges.find(g=>g.id===state.selectedGauge)||null;const stageOrder=['STOP_RUN','ABSORPTION','IMBALANCE','STRUCTURE_CONFIRMATION','RISK_ENGINE'];const flow='<div class="ti-flow">'+stageOrder.map((name,index)=>{const s=item.stages?.[name];const cls=s?.passed?'pass':item.failedStage===name?'fail':'';return (index?'<span class="ti-flow-arrow">→</span>':'')+'<span class="ti-flow-step '+cls+'">'+esc(stageLabels[name])+'</span>';}).join('')+'</div>';return '<div class="ti-selected-head"><div><span class="ti-selected-symbol" dir="ltr">'+esc(item.symbol)+'</span><div class="ti-selected-meta">'+esc(item.timeframe||'—')+' → '+esc(item.contextTimeframe||'—')+' · '+esc(item.dataMode||'—')+'</div></div><span class="ti-pill">Selected Scanner Result</span></div><div class="ti-shell"><section class="ti-master"><div class="ti-gauge" style="width:170px;height:170px;--gauge-score:'+Math.max(0,Math.min(100,Number(master.score||0)))+';--gauge-color:'+gaugeColor(masterGauge)+'"><div class="ti-gauge-core"><span class="ti-score" style="font-size:36px">'+number(master.score||0,0)+'</span><span class="ti-direction">'+esc(master.direction||'NO TRADE')+'</span><span class="ti-confidence">'+esc((master.status||'SCANNING').replaceAll('_',' '))+'</span></div></div><h4>Trade Readiness</h4><div class="ti-master-meta"><span class="ti-pill">Mandatory '+esc(master.mandatoryCompleted??0)+'/'+esc(master.mandatoryTotal??0)+'</span><span class="ti-pill">Execution BLOCKED</span><span class="ti-pill">PAPER TRADING</span></div>'+flow+'</section><section class="ti-grid-wrap"><div class="ti-grid">'+gauges.map(gaugeMarkup).join('')+'</div></section></div>'+detailMarkup(selectedGauge);}
  function opportunityMarkup(item){const passed=item.pipelinePassed===true;const failed=item.failedStage||'NONE';const stage=item.currentStage||'STOP_RUN';return '<button type="button" class="sm-opportunity '+(passed?'passed ':'')+(state.selectedSymbol===item.symbol?'selected':'')+'" data-symbol="'+esc(item.symbol)+'"><div><div class="sm-opportunity-symbol" dir="ltr">'+esc(item.symbol)+'</div><div class="sm-opportunity-family">'+esc(item.direction||'—')+' · '+esc(item.dataMode||'—')+'</div></div><div><strong>'+esc(passed?'PIPELINE COMPLETE':(item.reason||'PIPELINE REJECTED'))+'</strong><div class="sm-opportunity-family">'+esc(item.setupFamily||'INSTITUTIONAL FLOW')+'</div></div><div class="sm-opportunity-cell"><span>SCORE</span><strong>'+number(item.setupScore,1)+'</strong></div><div class="sm-opportunity-cell"><span>LAST PASSED</span><strong class="sm-stage-watch">'+esc(stageLabels[stage]||stage)+'</strong></div><div class="sm-opportunity-cell"><span>FAILED STAGE</span><strong class="'+(passed?'sm-stage-pass':'sm-stage-fail')+'">'+esc(passed?'NONE':(stageLabels[failed]||failed))+'</strong></div><div class="sm-opportunity-cell"><span>ENTRY / SL</span><strong dir="ltr">'+cash(item.entry)+' · '+cash(item.stopLoss)+'</strong></div><div class="sm-opportunity-cell"><span>TP / RR</span><strong dir="ltr">'+cash(item.takeProfit)+' · '+number(item.rewardRisk,2)+'</strong></div></button>';}
  function bindInteractions(){document.querySelectorAll('[data-symbol]').forEach(button=>button.addEventListener('click',()=>{state.selectedSymbol=button.dataset.symbol;state.selectedGauge=null;renderBody();}));document.querySelectorAll('[data-gauge-id]').forEach(button=>button.addEventListener('click',()=>{state.selectedGauge=button.dataset.gaugeId;renderBody();const detail=document.querySelector('.ti-detail');if(detail)detail.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});}));}
  function renderBody(){const content=document.getElementById('smartMoneyObservationContent');if(!content)return;const latest=state.latest;const items=state.items;const lastRun=latest?.recordedAt||latest?.evaluatedAt;const summary='<div class="sm-observation-summary"><div class="sm-observation-metric"><span>المحرك</span><strong>'+esc(latest?.engine||'INSTITUTIONAL FLOW')+'</strong></div><div class="sm-observation-metric"><span>الفريم</span><strong>'+esc(latest?.timeframe||'—')+'</strong></div><div class="sm-observation-metric"><span>الأسهم المحللة</span><strong>'+esc(latest?.evaluatedSymbols??0)+'</strong></div><div class="sm-observation-metric"><span>السلسلة المكتملة</span><strong>'+esc(latest?.completedCandidates??0)+'</strong></div><div class="sm-observation-metric"><span>آخر تحليل</span><strong>'+esc(lastRun?new Date(lastRun).toLocaleTimeString('en-US'):'—')+'</strong></div></div>';const distribution=stageDistribution(latest);if(!items.length){content.innerHTML=summary+distribution+'<div class="sm-observation-empty">لا توجد نتائج مؤهلة للعرض في آخر فحص.</div>';return;}if(!state.selectedSymbol||!items.some(item=>item.symbol===state.selectedSymbol))state.selectedSymbol=items[0].symbol;const selected=items.find(item=>item.symbol===state.selectedSymbol)||items[0];content.innerHTML=summary+distribution+intelligenceMarkup(selected)+'<div class="sm-opportunity-list">'+items.map(opportunityMarkup).join('')+'</div>';bindInteractions();}
  function render(status){ensurePanel();state.latest=status?.latest||null;state.items=Array.isArray(state.latest?.topOpportunities)?state.latest.topOpportunities:[];renderBody();}
  async function load(){try{const response=await fetch('/api/scanner/status',{cache:'no-store'});const data=await response.json();if(response.ok&&data.ok)render(data.scanner?.smartMoneyObservation||null);}catch{ensurePanel();}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensurePanel();load();});else{ensurePanel();load();}
  setInterval(load,60000);
})();
</script>`;

export async function enhanceSmartMoneyDashboard(response) {
  const contentType = response.headers.get('content-type') || '';
  if (!contentType.includes('text/html')) return response;
  const html = await response.text();
  if (html.includes('smartMoneyObservationScript')) return new Response(html, response);
  const withStyle = html.includes('</head>') ? html.replace('</head>', `${OVERLAY_STYLE}</head>`) : `${OVERLAY_STYLE}${html}`;
  const enhanced = withStyle.includes('</body>') ? withStyle.replace('</body>', `${OVERLAY_SCRIPT}</body>`) : `${withStyle}${OVERLAY_SCRIPT}`;
  const headers = new Headers(response.headers);
  headers.delete('content-length');
  return new Response(enhanced, { status: response.status, statusText: response.statusText, headers });
}
