export const stocks = [
  { symbol: 'QS', company: 'QuantumScape', sector: 'Battery Technology', price: 6.05, change: 2.72 },
  { symbol: 'PATH', company: 'UiPath', sector: 'Automation', price: 12.04, change: -0.99 },
  { symbol: 'LYFT', company: 'Lyft', sector: 'Mobility', price: 15.19, change: -1.56 },
  { symbol: 'SOFI', company: 'SoFi Technologies', sector: 'FinTech', price: 17.64, change: 3.70 },
  { symbol: 'RIVN', company: 'Rivian Automotive', sector: 'EV', price: 17.76, change: 3.02 },
  { symbol: 'SMCI', company: 'Super Micro Computer', sector: 'AI Infrastructure', price: 25.50, change: 7.01 },
  { symbol: 'CELH', company: 'Celsius Holdings', sector: 'Consumer', price: 28.02, change: -4.76 },
  { symbol: 'U', company: 'Unity Software', sector: 'Software', price: 29.87, change: 0.20 },
  { symbol: 'HIMS', company: 'Hims & Hers Health', sector: 'Health', price: 32.73, change: 0.09 },
  { symbol: 'ASTS', company: 'AST SpaceMobile', sector: 'Space', price: 63.34, change: 10.31 },
  { symbol: 'CAVA', company: 'CAVA Group', sector: 'Restaurants', price: 63.69, change: 0.28 },
  { symbol: 'CARR', company: 'Carrier Global', sector: 'Industrials', price: 66.69, change: -0.43 },
  { symbol: 'NFLX', company: 'Netflix', sector: 'Media', price: 68.67, change: 1.58 },
  { symbol: 'RKLB', company: 'Rocket Lab', sector: 'Space', price: 69.12, change: 5.14 },
  { symbol: 'UBER', company: 'Uber Technologies', sector: 'Mobility', price: 71.55, change: -0.86 },
  { symbol: 'TTAN', company: 'ServiceTitan', sector: 'Software', price: 72.96, change: -8.18 },
  { symbol: 'CRWV', company: 'CoreWeave', sector: 'AI', price: 79.58, change: 8.92 },
  { symbol: 'INTC', company: 'Intel', sector: 'Semiconductors', price: 105.45, change: 8.64 },
  { symbol: 'HOOD', company: 'Robinhood', sector: 'FinTech', price: 106.36, change: 7.13 },
  { symbol: 'KLIC', company: 'Kulicke and Soffa', sector: 'Semiconductors', price: 108.54, change: 8.47 },
  { symbol: 'WMT', company: 'Walmart', sector: 'Retail', price: 110.39, change: -1.61 },
  { symbol: 'BABA', company: 'Alibaba', sector: 'E-Commerce', price: 117.97, change: -1.97 },
  { symbol: 'DUOL', company: 'Duolingo', sector: 'Growth', price: 124.71, change: -6.86 },
  { symbol: 'PLTR', company: 'Palantir', sector: 'AI', price: 132.66, change: -1.62 },
  { symbol: 'XOM', company: 'Exxon Mobil', sector: 'Energy', price: 151.71, change: 2.26 },
  { symbol: 'QCOM', company: 'Qualcomm', sector: 'Semiconductors', price: 173.50, change: 1.87 },
  { symbol: 'SHOP', company: 'Shopify', sector: 'E-Commerce', price: 173.74, change: -0.82 },
  { symbol: 'CVX', company: 'Chevron', sector: 'Energy', price: 191.07, change: 0.72 },
  { symbol: 'NVDA', company: 'NVIDIA', sector: 'Semiconductors', price: 207.29, change: 1.97 },
  { symbol: 'AMZN', company: 'Amazon', sector: 'E-Commerce', price: 247.55, change: -0.98 },
  { symbol: 'SNOW', company: 'Snowflake', sector: 'Cloud', price: 271.73, change: -0.95 },
  { symbol: 'AAPL', company: 'Apple', sector: 'Technology', price: 327.74, change: 0.35 },
  { symbol: 'GOOGL', company: 'Alphabet', sector: 'Technology', price: 347.15, change: -1.38 },
  { symbol: 'TSLA', company: 'Tesla', sector: 'EV', price: 378.93, change: 2.53 }
].map((stock) => ({
  ...stock,
  score: null,
  signal: 'WAIT',
  timeframe: '15m',
  entry: null,
  stop: null,
  target: null,
  reason: 'CONNECT FINNHUB TO START MOE',
  engineReady: false
}));

export function createCustomStock(symbol) {
  return {
    symbol,
    company: symbol,
    sector: 'Custom',
    price: 0,
    change: 0,
    score: null,
    signal: 'WAIT',
    timeframe: '15m',
    entry: null,
    stop: null,
    target: null,
    reason: 'WAITING FOR FINNHUB DATA',
    engineReady: false
  };
}
